version: 2

sources:
  - name: weather
    schema: main
    tables:
      - name: weather_raw
        columns:
          - name: datetime
            tests:
              - not_null
          - name: temperature
            tests:
              - not_null
          - name: precipitation
            tests:
              - not_null
          - name: wind_speed
            tests:
              - not_null

